FROM rabbitmq:3-management

RUN rabbitmq-plugins enable --offline rabbitmq_stomp

EXPOSE 5672 15672 61613



#RUN rabbitmq-plugins enable --offline rabbitmq_management
#RUN rabbitmq-plugins enable --offline rabbitmq_web_stomp

#EXPOSE 5672 15672 61613