spring:
  application:
    name: totalhubsite
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:total-hu-site-dev-db;MODE=MYSQL
    username: admin
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true